---
- name: Install nginx
  hosts: all
  become: true
  vars_files:
    - vars/all_temp.yml

  tasks:
    - block: # ==== Block install NGINX ====
        - name: add nginx apt-key
          apt_key:
            url: https://nginx.org/keys/nginx_signing.key
            state: present

        - name: add nginx apt repsitory
          apt_repository:
            repo: "deb http://nginx.org/packages/mainline/ubuntu xenial nginx"
            state: present
            filename: nginx
            update_cache: yes

        - name: Installing nginx
          apt:
            allow_unauthenticated: yes
            name: nginx
            state: present
          notify: nginx start

    - block: # ==== Block replacing NGINX configs ====
        - name: Removing default nginx config
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /etc/nginx/nginx.conf
            - /etc/nginx/conf.d/default
          notify: nginx reloaded

        - name: Exported nginx conf
          vars:
            vhost_name: "{{ item.vhost_name }}"
            vhost_root: "{{ item.vhost_root }}"
          template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: root
            group: root
            mode: 0644
          loop:
            - {
                src: "vhost_temp.j2",
                dest: "{{ vhost_p.vhost_path_a }}",
                vhost_name: "{{ vhost_n.vhost_name_a }}",
                vhost_root: "{{ vhost_r.vhost_root_a }}",
              }
            - {
                src: "vhost_temp.j2",
                dest: "{{ vhost_p.vhost_path_u }}",
                vhost_name: "{{ vhost_n.vhost_name_u }}",
                vhost_root: "{{ vhost_r.vhost_root_u }}",
              }
            - { src: "nginx_temp.conf.j2", dest: "/etc/nginx/nginx.conf" }
          notify: nginx reloaded

  handlers:
    - name: nginx reloaded
      service:
        name: nginx
        state: reloaded

    - name: nginx start
      service:
        name: nginx
        enabled: yes
        state: started
